<a href="https://colab.research.google.com/github/ris2002/RNN_Scratch_Using_numpy_Pytorch/blob/main/RNN_Transformer_From_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *RNN* Architecture- Numpy


Forward Pass

First Data Preparation, Tokenisation and converting to Embeddings

In [ ]:
import kagglehub
import os
# Download latest version
path = kagglehub.dataset_download("swimmingwhale/dinosaur-island")
file_path = os.path.join(path, "dinos.txt")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'dinosaur-island' dataset.
Path to dataset files: /kaggle/input/dinosaur-island


In [ ]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
df=pd.read_csv(file_path,header=None,names=['name'])# in read_csv func names param helps to mannually provide a col name


In [ ]:
df['name'][12]

'Acristavus'

In [ ]:
df['name'].shape

(1536,)

In [ ]:
char_list=[]
for name in df['name']:
  clean_name=name.lower()
  d_array=np.array(list(clean_name))#dummy array
  char_list.append(d_array)


In [ ]:
char_list

[array(['a', 'a', 'c', 'h', 'e', 'n', 'o', 's', 'a', 'u', 'r', 'u', 's'],
       dtype='<U1'),
 array(['a', 'a', 'r', 'd', 'o', 'n', 'y', 'x'], dtype='<U1'),
 array(['a', 'b', 'd', 'a', 'l', 'l', 'a', 'h', 's', 'a', 'u', 'r', 'u',
        's'], dtype='<U1'),
 array(['a', 'b', 'e', 'l', 'i', 's', 'a', 'u', 'r', 'u', 's'], dtype='<U1'),
 array(['a', 'b', 'r', 'i', 'c', 't', 'o', 's', 'a', 'u', 'r', 'u', 's'],
       dtype='<U1'),
 array(['a', 'b', 'r', 'o', 's', 'a', 'u', 'r', 'u', 's'], dtype='<U1'),
 array(['a', 'b', 'y', 'd', 'o', 's', 'a', 'u', 'r', 'u', 's'], dtype='<U1'),
 array(['a', 'c', 'a', 'n', 't', 'h', 'o', 'p', 'h', 'o', 'l', 'i', 's'],
       dtype='<U1'),
 array(['a', 'c', 'h', 'e', 'l', 'o', 'u', 's', 'a', 'u', 'r', 'u', 's'],
       dtype='<U1'),
 array(['a', 'c', 'h', 'e', 'r', 'o', 'r', 'a', 'p', 't', 'o', 'r'],
       dtype='<U1'),
 array(['a', 'c', 'h', 'i', 'l', 'l', 'e', 's', 'a', 'u', 'r', 'u', 's'],
       dtype='<U1'),
 array(['a', 'c', 'h', 'i', 'l', 'l', 'o',

In [ ]:
all_chars=set()
all_chars.add('\n')
for name in char_list:
  for ch in name:
    all_chars.add(ch)
chars=sorted(list(all_chars))

In [ ]:
chars

['\n',
 np.str_('a'),
 np.str_('b'),
 np.str_('c'),
 np.str_('d'),
 np.str_('e'),
 np.str_('f'),
 np.str_('g'),
 np.str_('h'),
 np.str_('i'),
 np.str_('j'),
 np.str_('k'),
 np.str_('l'),
 np.str_('m'),
 np.str_('n'),
 np.str_('o'),
 np.str_('p'),
 np.str_('q'),
 np.str_('r'),
 np.str_('s'),
 np.str_('t'),
 np.str_('u'),
 np.str_('v'),
 np.str_('w'),
 np.str_('x'),
 np.str_('y'),
 np.str_('z')]

In [ ]:
char_to_ix={ch:i for i,ch in enumerate(chars)}
ix_to_char={i:ch for i,ch in enumerate(chars)}

In [ ]:
char_to_ix

{'\n': 0,
 np.str_('a'): 1,
 np.str_('b'): 2,
 np.str_('c'): 3,
 np.str_('d'): 4,
 np.str_('e'): 5,
 np.str_('f'): 6,
 np.str_('g'): 7,
 np.str_('h'): 8,
 np.str_('i'): 9,
 np.str_('j'): 10,
 np.str_('k'): 11,
 np.str_('l'): 12,
 np.str_('m'): 13,
 np.str_('n'): 14,
 np.str_('o'): 15,
 np.str_('p'): 16,
 np.str_('q'): 17,
 np.str_('r'): 18,
 np.str_('s'): 19,
 np.str_('t'): 20,
 np.str_('u'): 21,
 np.str_('v'): 22,
 np.str_('w'): 23,
 np.str_('x'): 24,
 np.str_('y'): 25,
 np.str_('z'): 26}

In [ ]:
ix_to_char

{0: '\n',
 1: np.str_('a'),
 2: np.str_('b'),
 3: np.str_('c'),
 4: np.str_('d'),
 5: np.str_('e'),
 6: np.str_('f'),
 7: np.str_('g'),
 8: np.str_('h'),
 9: np.str_('i'),
 10: np.str_('j'),
 11: np.str_('k'),
 12: np.str_('l'),
 13: np.str_('m'),
 14: np.str_('n'),
 15: np.str_('o'),
 16: np.str_('p'),
 17: np.str_('q'),
 18: np.str_('r'),
 19: np.str_('s'),
 20: np.str_('t'),
 21: np.str_('u'),
 22: np.str_('v'),
 23: np.str_('w'),
 24: np.str_('x'),
 25: np.str_('y'),
 26: np.str_('z')}

In [ ]:
name = char_list[0]
print(name)

['a' 'a' 'c' 'h' 'e' 'n' 'o' 's' 'a' 'u' 'r' 'u' 's']


In [ ]:
X = [char_to_ix[ch] for ch in name]
Y = [char_to_ix[ch] for ch in name[1:]] + [char_to_ix['\n']]

print("X:", np.shape(np.array(X)))
print("Y:", np.shape(np.array(Y)))
print("X:", X)
print("Y:", Y)



X: (13,)
Y: (13,)
X: [1, 1, 3, 8, 5, 14, 15, 19, 1, 21, 18, 21, 19]
Y: [1, 3, 8, 5, 14, 15, 19, 1, 21, 18, 21, 19, 0]


Model Architecture



In [ ]:
import numpy as np
# hidden layer with activation function
class Hidden_Layer:
  def __init__(self,vocab_size,embed_size,hidden_size):
    #hidden_size is nothing but no. neurons
    self.bias=np.zeros((1,hidden_size))
    #Embeddingtable
    self.Wex=np.random.randn(vocab_size,embed_size)*0.01
    #Hidden-Hidden weights
    self.Whh=np.random.randn(hidden_size,hidden_size)*0.01
    # Embed-Hidden weights
    self.Wxh=np.random.randn(embed_size,hidden_size)*0.01

  def forward(self,X_idx,h0=None):
    T=len(X_idx)
    H=self.Whh.shape[0]
    if h0 is None:
      h_prev=np.zeros((1,H))
    else:
      h_prev=h0.reshape(1,H)
    hs=np.zeros((T, H))
    self.cache=[]
    for t in range(T):
      idx=X_idx[t]
      e_t=self.Wex[idx:idx+1, :]
      a_t=e_t@self.Wxh+h_prev@self.Whh+self.bias
      h_t=a_t
      hs[t]=h_t
      self.cache.append((idx, e_t, h_prev, a_t, h_t))
      h_prev=h_t
    return hs
  def backward(self, dinputs):
    self.dWxh  = np.zeros_like(self.Wxh)
    self.dWhh  = np.zeros_like(self.Whh)
    self.dbias = np.zeros_like(self.bias)
    dh_next    = np.zeros((1, self.Whh.shape[0]))

    for i in reversed(range(len(self.cache))):
        idx, e_t, h_prev, a_t, h_t = self.cache[i]

        dh = dinputs[i] + dh_next

        self.dWxh  += e_t.T    @ dh
        self.dWhh  += h_prev.T @ dh
        self.dbias += np.sum(dh, axis=0, keepdims=True)

        dh_next = dh @ self.Whh.T

    return self.dWxh, self.dWhh, self.dbias


class Output_Layer():
  def __init__(self,hidden_size,vocab_size):
    self.weights=np.random.randn(hidden_size,vocab_size)*0.01
    self.bias=np.zeros((1,vocab_size))
  def forward(self,hidden_state):
    self.inputs=hidden_state
    self.output=np.dot(self.inputs,self.weights)+self.bias
    return self.output
  def backward(self,dinputs):

    self.dweights = self.inputs.T @ dinputs
    self.dbias = np.sum(dinputs, axis=0, keepdims=True)
    do_dh=self.weights.T
    op = dinputs @ do_dh
    return op
class Tanh_Activation_Function():
  def forward(self,inputs):
    self.outputs=np.tanh(inputs)
    return self.outputs
  def backward(self,dinputs):
    tanh_z=self.outputs
    dtanh_dzt=(1-(tanh_z**2))
    op=dtanh_dzt*dinputs
    return op

class Softmax_Layer:
  def forward(self,inputs):
    shifted = inputs - np.max(inputs, axis=1, keepdims=True)
    exp_vals=np.exp(shifted)
    self.output=exp_vals/np.sum(exp_vals,keepdims=True,axis=1)
    return self.output
  def backward(self,dvalues):
    self.dinputs = np.empty_like(dvalues)
    for index, (single_output, single_dvalue) in enumerate(
            zip(self.output, dvalues)
        ):
      single_output = single_output.reshape(-1, 1)
      jacobian_matrix = (
                np.diagflat(single_output)
                - np.dot(single_output, single_output.T)
            )
      self.dinputs[index] = np.dot(jacobian_matrix, single_dvalue)
      return self.dinputs
class Categorical_Cross_Entropy:
  def forward(self,y_pred,y_true):
    clipped_val=np.clip(y_pred,1e-7, 1 - 1e-7)
    samples = len(y_pred)
    clipped_vals=np.clip(y_pred,1e-7, 1 - 1e-7)
    if len(y_true.shape)==1:
      correct_confidences=clipped_vals[range(samples),y_true]
    elif len(y_true.shape)==2:
      correct_confidences=np.sum(clipped_vals * y_true, axis=1)
    data_loss = -np.log(correct_confidences)
    output=np.mean(data_loss)
    return output
  def backward(self,y_pred,y_true):
    samples = len(y_pred)
    labels=len(y_pred[0])
    #np.eye(n) creates an identity matrix with diamenntios n*n
    if len(y_true.shape) == 1:
      y_true=np.eye(labels)[y_true]
      self.d_values=-y_true/y_pred
      self.d_values=self.d_values/samples
      return self.d_values

class SGD:
    def __init__(self, learning_rate=0.01):
        self.lr = learning_rate

    def update(self, layer):
        layer.weights -= self.lr * layer.dweights
        layer.biases -= self.lr * layer.dbiases



Forward Pass

In [ ]:
hidden=Hidden_Layer(vocab_size=27,embed_size=10,hidden_size=100)
tanh=Tanh_Activation_Function()
output_layer=Output_Layer(hidden_size=100,vocab_size=27)
softmax=Softmax_Layer()
loss=Categorical_Cross_Entropy()
a=hidden.forward(X)
b=tanh.forward(a)
c=output_layer.forward(b)
d=softmax.forward(c)
e=loss.forward(d, np.array(Y))

In [ ]:
e

np.float64(3.2958473879086636)

In [ ]:
print("d shape:", d.shape)
print("Y shape:", np.array(Y).shape)

d shape: (13, 27)
Y shape: (13,)


In [ ]:
print("X:", X)
print("Y:", Y)

X: [1, 1, 3, 8, 5, 14, 15, 19, 1, 21, 18, 21, 19]
Y: [1, 3, 8, 5, 14, 15, 19, 1, 21, 18, 21, 19, 0]


In [ ]:

d1 = loss.backward(d, np.array(Y))


d2 = softmax.backward(d1)


d3 = output_layer.backward(d2)


d4 = tanh.backward(d3)

dWxh, dWhh, dbias = hidden.backward(d4)

In [ ]:
dWhh

array([[-8.11239131e-06,  2.39961667e-05,  2.83626761e-05, ...,
         4.90123614e-05, -7.43765551e-06,  3.37205202e-05],
       [ 5.08901459e-06,  2.34984719e-05, -1.48166424e-05, ...,
        -2.69052384e-06,  1.46232578e-05, -1.06127385e-05],
       [ 1.69175760e-06,  1.40195860e-05, -1.42695378e-06, ...,
         1.34388446e-05,  6.25614829e-06,  9.14790262e-06],
       ...,
       [-4.34689059e-06,  3.53387143e-05, -1.81231088e-05, ...,
         3.44811689e-05,  2.87270063e-05,  1.98154271e-05],
       [-1.25647843e-06,  5.36195376e-06, -9.55372962e-07, ...,
         8.47655549e-06, -1.29428569e-05, -1.53644493e-06],
       [ 3.58592011e-06, -2.42231612e-05, -1.52444927e-05, ...,
        -8.96974916e-06,  9.58800594e-06,  1.82092277e-07]])

In [ ]:

dbias

array([[ 7.93564502e-03, -6.29571259e-02,  1.23863481e-01,
        -8.62728123e-02, -1.71567917e-02,  7.54632747e-02,
        -8.76019085e-02,  4.73106651e-02, -6.28891865e-02,
         6.66347263e-02, -1.01253823e-01, -5.14953465e-02,
        -8.93876700e-02,  9.86123562e-02,  4.34230396e-02,
         5.08011162e-02,  8.41458374e-03,  9.01139492e-02,
        -1.17952394e-01, -6.34279183e-02, -3.43432122e-02,
         2.07596036e-02,  9.88279177e-02, -6.88111762e-02,
         4.50958275e-02, -1.40438848e-01, -4.36857713e-02,
         2.48080380e-02, -2.79803229e-02,  6.78819829e-02,
        -5.37385088e-02,  1.55486862e-01,  3.20818900e-02,
         5.48121344e-03, -3.02576613e-04, -1.51436100e-01,
         2.77965009e-02, -3.38740333e-02, -7.14449741e-02,
        -3.78911791e-02,  3.80222181e-02, -1.88742620e-02,
         1.13559085e-01, -8.47003086e-02,  1.67676301e-02,
        -6.61937040e-02,  3.71039039e-02, -1.16594297e-01,
        -4.17880480e-03, -9.47789881e-02, -4.79682325e-0

In [ ]:
dWxh

array([[-1.82868862e-04,  6.13413547e-04, -2.31709683e-04,
         8.14879712e-04, -1.80784453e-04,  3.91181386e-05,
         2.68714089e-04,  3.96387393e-04, -1.01956426e-03,
         1.83063964e-04,  9.62357952e-06, -1.15631139e-03,
         9.17434314e-04,  5.03742587e-04, -1.00325147e-03,
        -2.34112037e-04, -7.80649373e-05,  4.39128750e-04,
        -4.93759954e-04,  9.83196708e-05,  7.62514069e-06,
        -4.81550365e-04,  7.31011222e-05,  2.73520392e-04,
         5.29018665e-04,  3.91414459e-04,  5.75575420e-04,
        -1.29569524e-04,  5.53072164e-04,  6.62739232e-05,
        -1.24823875e-04,  3.57357783e-04, -2.96163325e-04,
        -9.32309163e-04,  1.88467925e-04, -2.43294315e-05,
        -2.52723679e-04,  1.14094683e-04,  2.49166664e-04,
         5.41571477e-04, -1.08641207e-04,  2.51378751e-04,
         1.76467817e-04,  3.85534397e-04,  1.64996197e-04,
         1.25259539e-04,  3.67033827e-04, -1.93537783e-05,
         1.65741625e-04,  3.14891617e-04,  4.74144084e-0

In [ ]:
for epoch in range(100):
    # forward
    a = hidden.forward(X)
    b = tanh.forward(a)
    c = output_layer.forward(b)
    d = softmax.forward(c)
    e = loss.forward(d, np.array(Y))

    # backward
    d1 = loss.backward(d, np.array(Y))
    d2 = softmax.backward(d1)
    d3 = output_layer.backward(d2)
    d4 = tanh.backward(d3)
    dWxh, dWhh, dbias = hidden.backward(d4)

    # update weights
    output_layer.weights -= 0.01 * output_layer.dweights
    output_layer.bias    -= 0.01 * output_layer.dbias
    hidden.Wxh           -= 0.01 * dWxh
    hidden.Whh           -= 0.01 * dWhh
    hidden.bias          -= 0.01 * dbias

    if epoch % 10 == 0:
        print(f"Epoch {epoch} Loss: {e}")

Epoch 0 Loss: 3.2958473879086636
Epoch 10 Loss: 2.9219762890958076
Epoch 20 Loss: 2.834770609492321
Epoch 30 Loss: 2.8710299393505796
Epoch 40 Loss: 2.7807690810549133
Epoch 50 Loss: 2.6245725772025374
Epoch 60 Loss: 2.4443326269066614
Epoch 70 Loss: 2.4518413303060576
Epoch 80 Loss: 4.228411250888888
Epoch 90 Loss: 11.195732788580063


/tmp/ipython-input-1707451116.py:113: RuntimeWarning: divide by zero encountered in divide
  self.d_values=-y_true/y_pred
/tmp/ipython-input-1707451116.py:113: RuntimeWarning: invalid value encountered in divide
  self.d_values=-y_true/y_pred
